import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarSection from "@/components/NavbarSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" 
    // className="dark"
    >
      <body className={inter.className}>
        <div className="relative w-full flex justify-center items-cente">
          <NavbarSection />
        </div>
        {children}
      </body>
    </html>
  );
}
